<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\TerminalBloops.ico</ApplicationIcon>
    <AssemblyName>TerminalBloops</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TerminalBloops.Core/TerminalBloops.Core.csproj" />
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <Resource Include="Assets\TerminalBloops.ico" />
  </ItemGroup>
</Project>
